---
title: "Yiying (Emma) Wu"
output: 
  html_document:
    toc: true
    toc_float: true
---

<link rel="stylesheet" href="academicons.css"/>
<link rel="stylesheet" href="styles.css" type="text/css">

<br>

### EDUCATION    
**The University of Texas Health Science Center at Houston, School of Public Health**   [*08/2024 – Present*]{style="float:right"}   
Doctor of Philosophy in Biostatistics                                                                                                       
Passed Preliminary Exam (08/2025)

Relevant Coursework: Survival Analysis, Statistical Computing, Statistical Inference, Multivariate Analysis, Stochastic Processes

**Columbia University - Mailman School of Public Health**  [*09/2022 - 05/2024*]{style="float:right"}              
Master of Public Health in Biostatistics, Certificate in Comparative Effectiveness Outcomes Research

Relevant Coursework: Applied Regression, Data Science, Analysis of Health Survey Data, Database(MySQL)

Honor: [Finalist for DataFest 2024](./resources/DataFest Award Certificates 2024 FINAL - Wu.pdf) (Top 4, Oral presentation at the ENAR Spring Meeting in Baltimore, Maryland, 03/2024),

[Delta Omega Honorary Society in Public Health](https://bcert.me/bc/html/show-badge.html?b=sorpqmkc) (07/2024)

**Shanghai University of Finance and Economics (SUFE) - School of Statistics and Management**
[*09/2018 - 07/2022*]{style="float:right"}

Bachelor of Science in Statistics

Relevant Coursework:  Real Analysis, Time Series, Survival Analysis, Machine Learning, Stochastic Processes

Honor: First Prize for The 5th Mathematical Modeling Competition of SUFE (Top 1%, 04/2019)

Certification: SUFE-Cambridge Leadership Online Programme (07/2020)

### PROFESSIONAL EXPERIENCE
**Wellness Equity Alliance | Data Analyst Intern**, California, United States  [*07/2023 - 09/2023*]{style="float:right"}

* Assisted in constructing the public health system for Vernon, California, and neighboring regions through demographic data analysis
* Used Google Earth (GIS) to display demographic data, mental health services, and food security resources

**Microsoft China, Microsoft AI and IoT Insider Lab | AI Analyst Intern**, Shanghai, China [*06/2021 - 08/2021*]{style="float:right"}

* Tested the Microsoft Azure cloud product “deep-voice-conversion-master” by converting audio text data into target text with a Convolutional Neural Network on a Linux system
* Wrote code in Python to convert the target text into the specified format in batch

**Hwabao Securities | Investment Analyst Intern**, Shanghai, China [*06/2020 - 08/2020*]{style="float:right"}

* Examined historical and current market supply and demand of the pharmaceutical industry
* Conducted statistical description/regression analysis to predict the risk of overseas investment and surplus capacity

### PROJECT EXPERIENCE

**PCA-based integration algorithm review, NMF model proposal and scHi-C + scRNA-seq integration | Graduate Research Assistant**, MD Anderson Cancer Center, Houston, TX, United States [*10/2024 – Present*]{style="float:right"}

*	Developed and evaluated statistical methods for integrating scHi-C and scRNA-seq datasets from mouse brain.
*	Implemented supervised PCA, reciprocal PCA, and non-negative matrix factorization (NMF) for multimodal integration.
*	Applied Seurat pipelines and scGAD transformation for single-cell 3D chromatin data preprocessing.
*	Future work includes combining NMF and anchor mapping for improved single-cell multi-omics integration.
                                                                                              
**BMI, Hypertension, and Cardiovascular Biomarkers: A Multivariate Analysis of the Framingham Study | Graduate Research Assistant**,  Houston, TX, United States [*04/2025-05/2025*]{style="float:right"}

* Applied MANOVA, Hotelling’s T², and MANCOVA to Framingham Heart Study data (n = 3,828).
*	Identified significant associations of BMI and hypertension with cholesterol, glucose, and heart rate.
*	Demonstrated independent and additive effects of obesity and hypertension on cardiovascular risk profiles.


**Predicting Methylation from Sequence and Gene Expression Using Deep Learning Methods | Research Assistant**, New York, NY, United States [*06/2023 - 05/2024*]{style="float:right"}

* Developed deep learning models that can accurately predict DNA methylation patterns based on genomic sequence and gene expression data
*	Utilized Python and Columbia University’s research computing resources to test, evaluate, and refine deep learning models, ensuring optimal performance and reliability

**Trends in Hypertension Control and Management Disparities in U.S. Adults: A NHANES Analysis from 1999-2020 | Graduate Researcher | [Report](./resources/ENAR2024_Project_report.pdf) | [GitHub](https://github.com/wuyiying2018/ENAR-DataFest) | [Video](https://www.youtube.com/watch?v=B0P4ieC4JbQ)**, New York, NY, United States [*12/2023 - 1/2024*]{style="float:right"}

* Utilized National Health and Nutrition Examination Survey (NHANES) data spanning 1999-2020 to investigate trends in stage 2 hypertension management among U.S. adults.
* Examined prevalence, awareness, and medication use related to hypertension, incorporating demographic factors and comorbidities as covariates in logistic regression models.
* Employed multiple imputation techniques to address missing data and adjusted for survey cycle weights.


**Analysis of Homelessness Crisis in California | Graduate Researcher | [Website](https://yuqingliu6.github.io/california_homelessness.io/index.html) | [GitHub](https://github.com/yuqingliu6/california_homelessness.io)**, New York, NY, United States [*10/2023 - 12/2023*]{style="float:right"}

* Analyzed two key datasets: the first capturing hospital encounters of California's homeless from 2019-2020, and the second providing demographic insights into those accessing homeless services from 2017-2023, to decipher trends in homelessness and healthcare utilization.
* Utilized Exploratory Data Analysis (EDA) and a Shiny App to identify demographic trends in California's homelessness services
* Applied the Yeo-Johnson transformation to linear regression data to enhance normality

**Research on Cluster Analysis of E-commerce customers based on RFM model | Undergraduate Researcher**, Shanghai, China [*03/2022 - 05/2022*]{style="float:right"}

* Drew word clouds about the most frequent words in the product description and brand column using the R package wordcloud2, to have a brief knowledge of the dataset
* Constructed a Recency, Frequency, and Monetary model (RFM) based on the data collected, and analyzed the model using the K-means algorithm
* Analyzed the groups of customer data after segmentation, and predicted their behavior in the future

**Prospects and Challenges of "Internet+" for Community Healthcare in Shanghai | Undergraduate Researcher**, Shanghai, China [*06/2021 - 08/2021*]{style="float:right"}

* Developed a questionnaire based on the Technology Acceptance Model (TAM) to investigate the acceptance of “Internet+” community healthcare by Shanghai residents
* Constructed a Structural Equation Model (SEM) of Shanghai residents' satisfaction with "Internet Community Clinic Services" using the TAM, and Analyzed the model using Partial Least Squares (PLS) written in R

**A Study of the Existing Machine Learning Models on Reading Comprehension | Undergraduate Researcher**, Shanghai, China [*06/2021 – 08/2021*]{style="float:right"}

* Conduct a literature review of current NLP methods 
* Leveraged external knowledge-enhanced models to speedily eliminate potential scenarios that are inconsistent with common sense, thereby dramatically reducing computational effort and improving efficiency
* Proposed an interpretable three-module multi-hop reading comprehension system, EPAr, which constructed an inference tree, proposed a single response candidate for each root-to-leaf chain, and consolidated key information from all inference chains for the prediction
                                                                                            
**Machine Learning or Regression? A Study of the Customer Satisfaction Based on Clinical Survey Data | Undergraduate Researcher**,  Shanghai, China [*01/2021 – 03/2021*]{style="float:right"}

* Constructed the Logistic/Probit regression model, decision tree model, random forest model, Catboost model, and
XGboost model to evaluate the factors affecting customer satisfaction with clinical services
* Compared the competitive advantages of Machine Learning models relative to traditional models, and concluded that Gender, Type of Disease, Online Support, Ease of Online Diagnose, and Effect of Diagnose are the main factors that affect patients’ satisfaction


**A Study on the Healthcare Service of Residents in Chongming District | Independent Team Leader**, Shanghai, China [*10/2020 – 12/2020 *]{style="float:right"}

* Led a team of 3 that conducted a field survey of 120 households to study the healthcare service of local residents
using STATA to perform descriptive analysis and statistical inference
* Mapped the relationship between healthcare coverage, the size of the community, and the average age of the community
* Analyzed the status and deficiencies of rural healthcare, and provided suggestions and solutions for policymakers to improve rural healthcare based on the analysis results
